services:
  - type: web
    plan: free
    env: node
    name: backend
    repo: https://github.com/fourhtyoz/Cringomba.git
    buildFilter:
      paths:
        - backend/**
    startCommand: cd backend; npm run build

  - type: web
    env: static
    name: frontend
    repo: https://github.com/fourhtyoz/Cringomba.git
    buildFilter:
      paths:
        - frontend/**
    buildCommand: cd frontend; npm run build
    staticPublishPath: ./frontend/build
    routes:
      - type: rewrite
        source: /*
        destination: /index.html