services:
  - type: web
    env: node
    name: backend
    repo: https://github.com/fourhtyoz/Cringomba.git
    buildFilter:
      paths:
        - backend/**
    startCommand: cd backend; npm run dev
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: fh-prod-db1
          property: connectionString
      - key: REDIS_URL
        fromService:
          name: fh-prod-redis1
          type: redis
          property: connectionString

  - type: web
    env: static
    name: frontend
    repo: https://github.com/fourhtyoz/Cringomba.git
    buildFilter:
      paths:
        - frontend/**
    buildCommand: cd frontend; npm run build
    staticPublishPath: ./frontend/build
    routes:
      - type: rewrite
        source: /*
        destination: /index.html